title:              DataBlog
email:              estebaneec11@hotmail.com
description:        Personal blog in data science and machine learning
author:             Esteban Rodriguez
baseurl:            ""
url:                "https://esjerome.github.io"

# Social Profiles
twitter_username:   
github_username:    esjerome
facebook_username:  
instagram_username:  
linkedin_username: esteban-rodriguez-mendoza

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
